# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import qualityinsight_pb2 as qualityinsight__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qualityinsight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataIngestionStub(object):
    """==================== 服务定义 ====================

    数据接入服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitProductData = channel.stream_unary(
                '/qualityinsight.DataIngestion/SubmitProductData',
                request_serializer=qualityinsight__pb2.ProductData.SerializeToString,
                response_deserializer=qualityinsight__pb2.IngestionSummary.FromString,
                _registered_method=True)
        self.SubmitSingleProduct = channel.unary_unary(
                '/qualityinsight.DataIngestion/SubmitSingleProduct',
                request_serializer=qualityinsight__pb2.ProductData.SerializeToString,
                response_deserializer=qualityinsight__pb2.IngestionResponse.FromString,
                _registered_method=True)


class DataIngestionServicer(object):
    """==================== 服务定义 ====================

    数据接入服务
    """

    def SubmitProductData(self, request_iterator, context):
        """双向流批量提交产品数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSingleProduct(self, request, context):
        """单条提交
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitProductData': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitProductData,
                    request_deserializer=qualityinsight__pb2.ProductData.FromString,
                    response_serializer=qualityinsight__pb2.IngestionSummary.SerializeToString,
            ),
            'SubmitSingleProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSingleProduct,
                    request_deserializer=qualityinsight__pb2.ProductData.FromString,
                    response_serializer=qualityinsight__pb2.IngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qualityinsight.DataIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qualityinsight.DataIngestion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataIngestion(object):
    """==================== 服务定义 ====================

    数据接入服务
    """

    @staticmethod
    def SubmitProductData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/qualityinsight.DataIngestion/SubmitProductData',
            qualityinsight__pb2.ProductData.SerializeToString,
            qualityinsight__pb2.IngestionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSingleProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qualityinsight.DataIngestion/SubmitSingleProduct',
            qualityinsight__pb2.ProductData.SerializeToString,
            qualityinsight__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerRegistryStub(object):
    """Worker 注册服务（C# Server 端托管，Python Worker 调用）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/qualityinsight.WorkerRegistry/RegisterWorker',
                request_serializer=qualityinsight__pb2.WorkerInfo.SerializeToString,
                response_deserializer=qualityinsight__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/qualityinsight.WorkerRegistry/Heartbeat',
                request_serializer=qualityinsight__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=qualityinsight__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WorkerRegistryServicer(object):
    """Worker 注册服务（C# Server 端托管，Python Worker 调用）
    """

    def RegisterWorker(self, request, context):
        """Worker 注册到服务器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker 心跳保活
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=qualityinsight__pb2.WorkerInfo.FromString,
                    response_serializer=qualityinsight__pb2.RegistrationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=qualityinsight__pb2.HeartbeatRequest.FromString,
                    response_serializer=qualityinsight__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qualityinsight.WorkerRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qualityinsight.WorkerRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerRegistry(object):
    """Worker 注册服务（C# Server 端托管，Python Worker 调用）
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qualityinsight.WorkerRegistry/RegisterWorker',
            qualityinsight__pb2.WorkerInfo.SerializeToString,
            qualityinsight__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qualityinsight.WorkerRegistry/Heartbeat',
            qualityinsight__pb2.HeartbeatRequest.SerializeToString,
            qualityinsight__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataProcessingStub(object):
    """数据处理服务（Python Worker 端托管，C# Server 调用）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessData = channel.unary_unary(
                '/qualityinsight.DataProcessing/ProcessData',
                request_serializer=qualityinsight__pb2.ProcessRequest.SerializeToString,
                response_deserializer=qualityinsight__pb2.ProcessResponse.FromString,
                _registered_method=True)


class DataProcessingServicer(object):
    """数据处理服务（Python Worker 端托管，C# Server 调用）
    """

    def ProcessData(self, request, context):
        """服务器指派处理任务给 Worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessData,
                    request_deserializer=qualityinsight__pb2.ProcessRequest.FromString,
                    response_serializer=qualityinsight__pb2.ProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qualityinsight.DataProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qualityinsight.DataProcessing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProcessing(object):
    """数据处理服务（Python Worker 端托管，C# Server 调用）
    """

    @staticmethod
    def ProcessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qualityinsight.DataProcessing/ProcessData',
            qualityinsight__pb2.ProcessRequest.SerializeToString,
            qualityinsight__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QualityQueryStub(object):
    """数据查询服务（Dashboard 使用）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboardSummary = channel.unary_unary(
                '/qualityinsight.QualityQuery/GetDashboardSummary',
                request_serializer=qualityinsight__pb2.DashboardQuery.SerializeToString,
                response_deserializer=qualityinsight__pb2.DashboardSummary.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/qualityinsight.QualityQuery/StreamAlerts',
                request_serializer=qualityinsight__pb2.AlertFilter.SerializeToString,
                response_deserializer=qualityinsight__pb2.AlertEvent.FromString,
                _registered_method=True)


class QualityQueryServicer(object):
    """数据查询服务（Dashboard 使用）
    """

    def GetDashboardSummary(self, request, context):
        """获取仪表盘摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """流式推送告警
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QualityQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboardSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardSummary,
                    request_deserializer=qualityinsight__pb2.DashboardQuery.FromString,
                    response_serializer=qualityinsight__pb2.DashboardSummary.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=qualityinsight__pb2.AlertFilter.FromString,
                    response_serializer=qualityinsight__pb2.AlertEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qualityinsight.QualityQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qualityinsight.QualityQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QualityQuery(object):
    """数据查询服务（Dashboard 使用）
    """

    @staticmethod
    def GetDashboardSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qualityinsight.QualityQuery/GetDashboardSummary',
            qualityinsight__pb2.DashboardQuery.SerializeToString,
            qualityinsight__pb2.DashboardSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qualityinsight.QualityQuery/StreamAlerts',
            qualityinsight__pb2.AlertFilter.SerializeToString,
            qualityinsight__pb2.AlertEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
